logging:
  level:
    root: DEBUG

spring:
  redis:
    host: localhost
    port: 6379
    username:
    password:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test_survey?characterEncoding=UTF-8
    username: root
    password: fshuai123
    pool:
      validation-query: SELECT 1
      enabled: true
#    url: r2dbcs:h2:mem:///testdb?allowMultiQueries=true&serverTimezone=Asia%2FShanghai&DB_CLOSE_DELAY=-1
#    username:
#    password:
#    pool:
#      max-size: 50
#      validation-query: select 1
#      max-acquire-time: 60s
#      max-idle-time: 10m

wechat:
  app-id: 
  app-secret: 

jwt:
  key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
